# 第一題：
題目：給定一個矩陣m，裡面的值都大於0。
請將矩陣m裡大於等於1的數字都變成1，小於1的變成0。
 
m = np.array([[0,1,10],[2,6,7]])
 
提示：使用巢狀迴圈(nested loop)加判斷式

In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

matrix = np.array([[0,1,10],[2,6,7]])

(m,n) = np.shape(matrix)

for i in range(m):
    for j in range(n):
        if(matrix[i][j]>=1):
            matrix[i][j] = 1
        elif(matrix[i][j]<1):
            matrix[i][j] = 0
            
print(matrix)

[[0 1 1]
 [1 1 1]]


# 第二題：
有A,B,C三個班級，每班皆有10個學生，期中考結束後，老師希望計算各班級每位學生的加權平均成績。
 
請隨機產生3個班級的成績單,每班10人,共五科,權重為weights=[0.25,0.25,0.25,0.15,0.10]。
請算出班級加權平均成績，並以一個array輸出。

In [2]:
grades = np.random.randint(0,100,(3,10,5))
weights=[0.25,0.25,0.25,0.15,0.10]
print(grades)

w_grades = grades * weights
avg_grades =np.sum(np.sum(w_grades,axis=2),axis=1)/10
print(avg_grades)

[[[24  0 96 44 61]
  [47 10 72 93 35]
  [65 83 40 63  8]
  [ 7 31 83 35 46]
  [ 9 50 23 51 85]
  [53 67 68 73 40]
  [76 88 69 77 36]
  [78 77 90 92 78]
  [77 17 94 29  0]
  [70 54 49 13 85]]

 [[85 21 10  4 58]
  [92  6 92 26 99]
  [58 10 54 14 65]
  [84  1 99 26 27]
  [83 40 23 84 72]
  [ 4 13 76 51 16]
  [84 77  3 87 28]
  [ 4 65 50 77 65]
  [48 58 27 26 89]
  [77 14 67 22 46]]

 [[48 93 40 28 20]
  [50 58 16 22 32]
  [97 38 71  5 83]
  [68 77  4 93 65]
  [53  1 30 29 44]
  [99 92 12 16 38]
  [38 67 74 90 40]
  [44 53 11 41 20]
  [11 55 76 81 83]
  [22 60 53 55  1]]]
[ 54.965  47.53   48.935]


# 挑戰題一：
請定義一個全班高微成績的函式，輸入是一個(3, 30, 3)的array，  
表示3個班級中30位學生的成績(小考，期中考，期末考)  。

目標輸出則是一個(3, 30, 1)的array，表示所有學生的期末成績，
期末成績計算方式如下：

1. 小考20%，期中考35%，期末考45%  
2. 期中考40%，期末考60%。  
擇優作為期末成績
 
Hint
* 可以用雙重for迴圈 分別跑過班級跟人
* 可以先設一個array裝算出來的成績
* 記得要用return 
* 請做個測試，檢驗你的結果，方便同學評分。

In [4]:
def grade_cal(list):
    w1 = [0.2, 0.35, 0.45]
    w2 = [0, 0.4, 0.6]

    
    g1 = list * w1
    g1 = np.sum(g1,axis=2)
    g2 = list * w2
    g2 = np.sum(g2,axis=2)
    m,n = np.shape(g1)
    result = np.zeros((m,n))
    
    for i in range(m):
        for j in range(n):
            result[i][j] = max(g1[i][j],g2[i][j])
    return result

grades = np.random.randint(0,100,(3,30,3))
print(grades)
grade_cal(grades)


[[[24 90 19]
  [73 68 82]
  [80 52 84]
  [40 91 51]
  [39  4 15]
  [22 26 13]
  [68  1 13]
  [92  2 40]
  [29 15  3]
  [ 9 76 30]
  [76  2 37]
  [26 35 10]
  [35 37 72]
  [24 76 80]
  [92 32 69]
  [33  7 87]
  [73 84 24]
  [ 7 88 33]
  [68  0 30]
  [ 0 81 25]
  [78 99 29]
  [25 96 98]
  [41 92 46]
  [79 69 75]
  [33 20 40]
  [95 23 30]
  [68 86  6]
  [83 57  7]
  [65 34 75]
  [68 15 24]]

 [[61 37 16]
  [34 13 72]
  [24 42  4]
  [94 54 68]
  [22 36 36]
  [58 52 60]
  [12 41 63]
  [ 5 42 81]
  [98  6 15]
  [ 8 16 90]
  [72 34 74]
  [63 29 12]
  [54 69 10]
  [49 76 35]
  [48 42 68]
  [ 6 15 32]
  [17 68 98]
  [42  5 79]
  [13 24 58]
  [78 80 77]
  [81 56 17]
  [38 12 64]
  [28  8 28]
  [75 41 29]
  [58 49 15]
  [52 80 43]
  [18 71 46]
  [ 9 98 68]
  [49 54 65]
  [65 97 89]]

 [[57 39 58]
  [46 33 81]
  [51  9 21]
  [89  9 98]
  [21 27 74]
  [57 76 73]
  [98 73 89]
  [ 2 73 19]
  [23 10 36]
  [ 8 90 61]
  [60 58 89]
  [55 81 75]
  [14 84  4]
  [91 36  1]
  [ 3  9 27]
  [44 33 19]
  [ 3 47

array([[ 47.4 ,  76.4 ,  72.  ,  67.  ,  15.95,  19.35,  19.8 ,  37.1 ,
         12.4 ,  48.4 ,  32.55,  21.95,  58.  ,  78.4 ,  60.65,  55.  ,
         54.8 ,  55.  ,  27.1 ,  47.4 ,  63.3 ,  97.2 ,  64.4 ,  73.7 ,
         32.  ,  40.55,  46.4 ,  39.7 ,  58.65,  29.65],
       [ 32.35,  48.4 ,  21.3 ,  68.3 ,  36.  ,  56.8 ,  54.2 ,  65.4 ,
         28.45,  60.4 ,  59.6 ,  28.15,  39.45,  52.15,  57.6 ,  25.2 ,
         86.  ,  49.4 ,  44.4 ,  78.25,  43.45,  43.2 ,  21.  ,  42.4 ,
         35.5 ,  57.8 ,  56.  ,  80.  ,  60.6 ,  92.2 ],
       [ 51.15,  61.8 ,  22.8 ,  65.05,  55.2 ,  74.2 ,  85.2 ,  40.6 ,
         25.6 ,  72.6 ,  76.6 ,  77.4 ,  36.  ,  31.25,  19.8 ,  28.9 ,
         72.2 ,  58.15,  81.  ,  65.35,  27.2 ,  50.6 ,  74.4 ,  57.8 ,
         46.35,  53.  ,  61.  ,  66.  ,  44.4 ,  28.75]])