In [53]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [54]:
x = np.arange(9.).reshape(3, 3)
x

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [55]:
np.where( x > 5 )

(array([2, 2, 2], dtype=int64), array([0, 1, 2], dtype=int64))

In [56]:
np.where(x < 5, x, -1)

array([[ 0.,  1.,  2.],
       [ 3.,  4., -1.],
       [-1., -1., -1.]])

In [57]:
np.nonzero(x)

(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [58]:
x[np.nonzero(x)]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [59]:
np.transpose(np.nonzero(x))

array([[0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [1, 2],
       [2, 0],
       [2, 1],
       [2, 2]], dtype=int64)

In [60]:
np.nonzero(np.array([[1,2,3],[4,5,6],[7,8,9]]))

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [61]:
a = [1,2,3]
b = [4,5,6]

In [62]:
zipped = zip(a,b)

In [63]:
for (i,j) in zipped:
    print("{},{}".format(i, j))

1,4
2,5
3,6


In [64]:
x[1,1]

4.0

In [65]:
x[1][1]

4.0