In [2]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [15]:
A = np.random.randn(100)

In [16]:
A

array([ 2.12197615,  1.69306415,  2.14197572,  0.35925276,  0.34570551,
        0.36675248, -0.74681747, -1.25187246,  0.79060189, -0.12228028,
        2.27440535, -1.18081558, -1.21113928, -0.06538693,  0.01063076,
       -0.95021602,  1.53729109, -0.47320454,  1.34611276, -0.07222718,
        0.02008376, -0.30462561, -0.34066177,  0.95827141,  0.46979438,
       -2.25429852, -0.14418886,  1.44633439,  0.61492753, -0.15844749,
       -0.05746784,  0.39544848, -0.65395876, -0.35404818, -0.11294366,
       -0.08434259,  0.27642603, -0.53066201,  0.27119196,  1.20036639,
       -1.03563883, -0.12408256,  2.11410311, -0.50204558,  0.45605761,
       -0.95350856, -0.98771814, -3.00522587, -0.65117484, -0.85110661,
       -1.31453231, -0.59099732, -0.46382538, -0.41923952, -2.69784133,
       -0.19932915,  1.32281726,  0.0495436 ,  1.63430424, -0.25310028,
       -0.46668247,  1.57601702,  0.23085318,  0.38021795,  0.0742604 ,
        0.08800425,  1.91299717, -0.38563051,  0.27995205,  0.20

In [18]:
A = 10*A + 50

In [19]:
A

array([ 71.21976154,  66.93064147,  71.4197572 ,  53.59252757,
        53.45705505,  53.66752482,  42.53182535,  37.48127539,
        57.90601886,  48.77719716,  72.74405348,  38.19184417,
        37.88860719,  49.34613073,  50.10630764,  40.49783981,
        65.37291089,  45.26795458,  63.46112757,  49.27772816,
        50.20083755,  46.95374386,  46.59338232,  59.58271414,
        54.6979438 ,  27.45701477,  48.55811137,  64.46334394,
        56.14927532,  48.41552512,  49.42532162,  53.95448481,
        43.4604124 ,  46.45951815,  48.87056341,  49.15657411,
        52.76426034,  44.69337995,  52.71191964,  62.00366387,
        39.64361167,  48.7591744 ,  71.14103106,  44.97954422,
        54.5605761 ,  40.46491435,  40.12281862,  19.9477413 ,
        43.48825161,  41.48893386,  36.85467686,  44.09002681,
        45.36174621,  45.80760483,  23.02158668,  48.00670855,
        63.22817264,  50.49543604,  66.34304242,  47.4689972 ,
        45.33317533,  65.76017016,  52.30853181,  53.80

In [7]:
A.shape

(100,)

In [8]:
A.shape = (5,20)

In [20]:
A

array([ 71.21976154,  66.93064147,  71.4197572 ,  53.59252757,
        53.45705505,  53.66752482,  42.53182535,  37.48127539,
        57.90601886,  48.77719716,  72.74405348,  38.19184417,
        37.88860719,  49.34613073,  50.10630764,  40.49783981,
        65.37291089,  45.26795458,  63.46112757,  49.27772816,
        50.20083755,  46.95374386,  46.59338232,  59.58271414,
        54.6979438 ,  27.45701477,  48.55811137,  64.46334394,
        56.14927532,  48.41552512,  49.42532162,  53.95448481,
        43.4604124 ,  46.45951815,  48.87056341,  49.15657411,
        52.76426034,  44.69337995,  52.71191964,  62.00366387,
        39.64361167,  48.7591744 ,  71.14103106,  44.97954422,
        54.5605761 ,  40.46491435,  40.12281862,  19.9477413 ,
        43.48825161,  41.48893386,  36.85467686,  44.09002681,
        45.36174621,  45.80760483,  23.02158668,  48.00670855,
        63.22817264,  50.49543604,  66.34304242,  47.4689972 ,
        45.33317533,  65.76017016,  52.30853181,  53.80

In [21]:
A.reshape(100,1)

array([[ 71.21976154],
       [ 66.93064147],
       [ 71.4197572 ],
       [ 53.59252757],
       [ 53.45705505],
       [ 53.66752482],
       [ 42.53182535],
       [ 37.48127539],
       [ 57.90601886],
       [ 48.77719716],
       [ 72.74405348],
       [ 38.19184417],
       [ 37.88860719],
       [ 49.34613073],
       [ 50.10630764],
       [ 40.49783981],
       [ 65.37291089],
       [ 45.26795458],
       [ 63.46112757],
       [ 49.27772816],
       [ 50.20083755],
       [ 46.95374386],
       [ 46.59338232],
       [ 59.58271414],
       [ 54.6979438 ],
       [ 27.45701477],
       [ 48.55811137],
       [ 64.46334394],
       [ 56.14927532],
       [ 48.41552512],
       [ 49.42532162],
       [ 53.95448481],
       [ 43.4604124 ],
       [ 46.45951815],
       [ 48.87056341],
       [ 49.15657411],
       [ 52.76426034],
       [ 44.69337995],
       [ 52.71191964],
       [ 62.00366387],
       [ 39.64361167],
       [ 48.7591744 ],
       [ 71.14103106],
       [ 44

In [22]:
A

array([ 71.21976154,  66.93064147,  71.4197572 ,  53.59252757,
        53.45705505,  53.66752482,  42.53182535,  37.48127539,
        57.90601886,  48.77719716,  72.74405348,  38.19184417,
        37.88860719,  49.34613073,  50.10630764,  40.49783981,
        65.37291089,  45.26795458,  63.46112757,  49.27772816,
        50.20083755,  46.95374386,  46.59338232,  59.58271414,
        54.6979438 ,  27.45701477,  48.55811137,  64.46334394,
        56.14927532,  48.41552512,  49.42532162,  53.95448481,
        43.4604124 ,  46.45951815,  48.87056341,  49.15657411,
        52.76426034,  44.69337995,  52.71191964,  62.00366387,
        39.64361167,  48.7591744 ,  71.14103106,  44.97954422,
        54.5605761 ,  40.46491435,  40.12281862,  19.9477413 ,
        43.48825161,  41.48893386,  36.85467686,  44.09002681,
        45.36174621,  45.80760483,  23.02158668,  48.00670855,
        63.22817264,  50.49543604,  66.34304242,  47.4689972 ,
        45.33317533,  65.76017016,  52.30853181,  53.80

In [23]:
A = A.reshape(100,1)

In [24]:
A

array([[ 71.21976154],
       [ 66.93064147],
       [ 71.4197572 ],
       [ 53.59252757],
       [ 53.45705505],
       [ 53.66752482],
       [ 42.53182535],
       [ 37.48127539],
       [ 57.90601886],
       [ 48.77719716],
       [ 72.74405348],
       [ 38.19184417],
       [ 37.88860719],
       [ 49.34613073],
       [ 50.10630764],
       [ 40.49783981],
       [ 65.37291089],
       [ 45.26795458],
       [ 63.46112757],
       [ 49.27772816],
       [ 50.20083755],
       [ 46.95374386],
       [ 46.59338232],
       [ 59.58271414],
       [ 54.6979438 ],
       [ 27.45701477],
       [ 48.55811137],
       [ 64.46334394],
       [ 56.14927532],
       [ 48.41552512],
       [ 49.42532162],
       [ 53.95448481],
       [ 43.4604124 ],
       [ 46.45951815],
       [ 48.87056341],
       [ 49.15657411],
       [ 52.76426034],
       [ 44.69337995],
       [ 52.71191964],
       [ 62.00366387],
       [ 39.64361167],
       [ 48.7591744 ],
       [ 71.14103106],
       [ 44

In [25]:
A.reshape(1,100)

array([[ 71.21976154,  66.93064147,  71.4197572 ,  53.59252757,
         53.45705505,  53.66752482,  42.53182535,  37.48127539,
         57.90601886,  48.77719716,  72.74405348,  38.19184417,
         37.88860719,  49.34613073,  50.10630764,  40.49783981,
         65.37291089,  45.26795458,  63.46112757,  49.27772816,
         50.20083755,  46.95374386,  46.59338232,  59.58271414,
         54.6979438 ,  27.45701477,  48.55811137,  64.46334394,
         56.14927532,  48.41552512,  49.42532162,  53.95448481,
         43.4604124 ,  46.45951815,  48.87056341,  49.15657411,
         52.76426034,  44.69337995,  52.71191964,  62.00366387,
         39.64361167,  48.7591744 ,  71.14103106,  44.97954422,
         54.5605761 ,  40.46491435,  40.12281862,  19.9477413 ,
         43.48825161,  41.48893386,  36.85467686,  44.09002681,
         45.36174621,  45.80760483,  23.02158668,  48.00670855,
         63.22817264,  50.49543604,  66.34304242,  47.4689972 ,
         45.33317533,  65.76017016,  52.