In [25]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [26]:
A = np.zeros((10,5))
for i in range(10):
    A[i] = np.random.randint(0,100,5)

In [27]:
A

array([[ 12.,  11.,  28.,   6.,  53.],
       [ 12.,  27.,  18.,   8.,   3.],
       [ 60.,  59.,  90.,  85.,  49.],
       [ 95.,  24.,  15.,  54.,  55.],
       [ 24.,   9.,  37.,  23.,  60.],
       [ 66.,  46.,  73.,  23.,   1.],
       [ 87.,  17.,  64.,  96.,  93.],
       [ 82.,  21.,   1.,  57.,  23.],
       [ 87.,  79.,  65.,   5.,  68.],
       [ 32.,  14.,  54.,  76.,  27.]])

In [28]:
B = np.zeros((10,5))
for i in range(10):
    B[i] = np.random.randint(0,100,5)

In [29]:
B

array([[ 35.,  85.,  33.,  76.,  28.],
       [ 15.,  82.,  84.,  90.,   9.],
       [ 59.,  62.,  76.,  90.,   2.],
       [ 71.,  21.,  86.,  33.,  45.],
       [ 28.,  82.,  13.,  75.,  40.],
       [ 72.,  21.,  29.,  41.,  43.],
       [ 41.,  76.,  67.,  30.,  12.],
       [ 76.,  23.,  44.,  61.,  39.],
       [ 25.,  67.,  41.,  88.,  61.],
       [ 99.,  31.,  35.,  36.,  27.]])

In [30]:
C = np.zeros((10,5))
for i in range(10):
    C[i] = np.random.randint(0,100,5)

In [31]:
C

array([[ 15.,  45.,  73.,  95.,  33.],
       [ 58.,  77.,  11.,  40.,  35.],
       [ 57.,  96.,  79.,  37.,  24.],
       [  5.,  57.,  47.,  59.,  83.],
       [ 69.,  30.,  70.,  28.,  96.],
       [  6.,  87.,  71.,  89.,  28.],
       [ 51.,  66.,  68.,  29.,  23.],
       [ 23.,  40.,  38.,  34.,  10.],
       [ 71.,   4.,  84.,  64.,   2.],
       [ 52.,  96.,  43.,  54.,  60.]])

In [32]:
weights = np.array([0.25, 0.25, 0.25, 0.15, 0.1])

In [33]:
np.array([np.dot(A,weights), np.dot(B,weights), np.dot(B, weights)])

array([[ 18.95,  15.75,  69.9 ,  47.1 ,  26.95,  49.8 ,  65.7 ,  36.85,
         65.3 ,  39.1 ],
       [ 52.45,  59.65,  62.95,  53.95,  46.  ,  40.95,  51.7 ,  48.8 ,
         52.55,  49.35],
       [ 52.45,  59.65,  62.95,  53.95,  46.  ,  40.95,  51.7 ,  48.8 ,
         52.55,  49.35]])