In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x = np.array([[-3,2], [-6,5], [3,-4], [2,-8]])
y = np.array([1, 1, 2, 2])

In [3]:
x

array([[-3,  2],
       [-6,  5],
       [ 3, -4],
       [ 2, -8]])

In [4]:
y

array([1, 1, 2, 2])

In [5]:
from sklearn.svm import SVC

In [6]:
clf = SVC()

In [7]:
clf.fit(x, y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [8]:
clf.predict([[-3,2]])

array([1])

In [10]:
clf.predict(x)

array([1, 1, 2, 2])

In [11]:
clf.predict([[2.5,3]])

array([1])