In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(0.3, 10.3, 0.2)

array([  0.3,   0.5,   0.7,   0.9,   1.1,   1.3,   1.5,   1.7,   1.9,
         2.1,   2.3,   2.5,   2.7,   2.9,   3.1,   3.3,   3.5,   3.7,
         3.9,   4.1,   4.3,   4.5,   4.7,   4.9,   5.1,   5.3,   5.5,
         5.7,   5.9,   6.1,   6.3,   6.5,   6.7,   6.9,   7.1,   7.3,
         7.5,   7.7,   7.9,   8.1,   8.3,   8.5,   8.7,   8.9,   9.1,
         9.3,   9.5,   9.7,   9.9,  10.1])

In [4]:
x1, x2 = np.meshgrid(np.arange(0, 7, 0.02), np.arange(0, 3, 0.02))

In [6]:
x1

array([[ 0.  ,  0.02,  0.04, ...,  6.94,  6.96,  6.98],
       [ 0.  ,  0.02,  0.04, ...,  6.94,  6.96,  6.98],
       [ 0.  ,  0.02,  0.04, ...,  6.94,  6.96,  6.98],
       ..., 
       [ 0.  ,  0.02,  0.04, ...,  6.94,  6.96,  6.98],
       [ 0.  ,  0.02,  0.04, ...,  6.94,  6.96,  6.98],
       [ 0.  ,  0.02,  0.04, ...,  6.94,  6.96,  6.98]])

In [5]:
xx = [1,2,3,4]
yy = [5,6,7,8]
np.c_[xx, yy]

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [8]:
Z = clf.predict(np.c_[x1.ravel(), x2.ravel()])

NameError: name 'clf' is not defined