In [55]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [56]:
m=np.array([[0,1,10],[2,6,7]])

In [57]:
m = m >=1

In [58]:
print(m*1)

[[0 1 1]
 [1 1 1]]


In [59]:
m[0,2] == 1

True

In [60]:
m[0,2]*20

20

m[0,2]  matrics中的第0個array中的第2個元素

第二題

In [72]:
m = np.random.rand(3,10,5)
weights=[0.25,0.25,0.25,0.15,0.10]

In [62]:
avg_cls = []
for cls in m:
    avg_stu = []
    for stu in cls:
        avg_stu.append(np.dot(stu, weights))
    avg_cls.append(np.sum(avg_stu)/len(avg_stu))

In [63]:
print(avg_cls)

[0.45522850995714831, 0.44993207685818259, 0.47014611316052707]


In [64]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [65]:
m = np.random.rand(3,10,5)*100
weights=[0.25,0.25,0.25,0.15,0.10]

In [66]:
avg_cls = []
for cls in m:
    avg_stu = []
    for stu in cls:
        avg_stu.append(np.dot(stu, weights))
        print(len(avg_stu))
    avg_cls.append(np.sum(avg_stu)/len(avg_stu))

1
2
3
4
5
6
7
8
9
10
1
2
3
4
5
6
7
8
9
10
1
2
3
4
5
6
7
8
9
10


In [67]:
print(avg_stu)

[55.609334415836742, 74.287558861044261, 39.779670042507419, 56.432096165267112, 64.493727903220787, 40.329525513080128, 64.06060757396591, 59.552193265512791, 74.364823237302403, 36.266927376401433]


In [68]:
print(avg_cls)

[48.508480490635137, 50.948259721256072, 56.517646435413894]


In [69]:
print(m)

[[[  5.74224557e+01   5.37883628e+01   5.93453639e+01   5.89795969e+01
     3.36477651e+01]
  [  4.86863544e+01   2.95168809e+00   3.15626119e+01   1.81736737e+01
     3.51247038e+01]
  [  7.15545158e+01   4.54173880e+00   1.00199296e+01   1.87597158e+01
     4.31003526e+01]
  [  8.96626725e+01   7.26527719e+01   7.37407662e+01   1.94243831e+01
     4.12654733e+01]
  [  4.77918589e+01   1.45906357e+01   2.88960134e+00   6.43867161e+01
     7.80606293e+01]
  [  6.44465569e+01   6.99705055e+01   8.97360803e+01   4.81587642e+01
     5.53155149e+01]
  [  8.99124027e+01   1.64091718e+01   6.87573261e+01   3.35595368e+01
     4.18748408e+01]
  [  1.05356583e+01   3.12569107e+01   9.89549931e+01   3.31546521e+01
     7.55404187e+01]
  [  9.26399893e+01   1.92467264e+01   9.28352147e+01   9.76883131e-02
     5.92414406e+01]
  [  3.51969412e+01   7.73564152e+01   2.10740269e+01   9.37512725e+01
     6.18229385e+00]]

 [[  9.28402853e+01   9.28608304e+01   4.80869949e+01   7.38404417e+01
     1.

挑戰題一

In [70]:
m=np.random.rand(3,30,3)*100
weights=[0.20,0.35,0.45]

In [71]:
print(m)

[[[ 30.74090601  67.07364607  51.94965136]
  [ 61.81698592   4.95812142   2.3171744 ]
  [ 83.59712299  99.30445025  41.85515921]
  [ 90.11227735  29.07699593  80.52369926]
  [  6.4494316   16.06077851  71.43589025]
  [ 73.37419766  90.20041237  61.7887303 ]
  [ 46.91307429  39.88012008  66.60882412]
  [ 93.94631004  45.26298744  93.06169953]
  [ 78.08783998  30.25579988  54.70765343]
  [ 85.91381036  35.44322674  82.01915432]
  [ 40.04637513  93.46472068  32.40859052]
  [  3.64553057  31.98502107  15.0232849 ]
  [ 94.51289888  15.97870613  69.5334773 ]
  [ 99.5210971   41.38336349  55.68110367]
  [ 20.15166791   4.8998084   20.31640572]
  [ 55.45763799  12.40575717  97.19738152]
  [ 36.95239385  23.97715192  97.57116431]
  [ 90.95199869  94.20201859  40.81287731]
  [ 26.17776625  65.19809032  64.53817254]
  [ 76.72150793  99.81818094  53.57758848]
  [ 33.49874121  61.62868661  98.32762823]
  [ 83.88774789  10.09512653  87.32374062]
  [ 29.56929243  57.44302789  68.06012645]
  [ 79.2474