In [71]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [72]:
def matrix_plus(*m):
    if len(m) != 2:
        raise Exception('請輸入兩個矩陣')
    if m[0].shape != (5,5) or m[1].shape != (5,5):
        raise Exception('請輸入5*5的矩陣')
    return m[0] + m[1]    

In [73]:
print(matrix_plus(np.random.randint(0,101,size=(5,5)), np.random.randint(0,101,size=(5,5))))

[[124  45  92 149 132]
 [128 104 123  91 139]
 [ 95 174 106 145 123]
 [166  33  87  26 157]
 [ 20  43  77 141  23]]


In [74]:
try:
    matrix_plus(np.random.randint(0,101,size=(5,3)), np.random.randint(0,101,size=(5,5)))
except Exception as e:
    print(e)

請輸入5*5的矩陣


In [75]:
try:
    matrix_plus(np.random.randint(0,101,size=(5,5)))
except Exception as e:
    print(e)

請輸入兩個矩陣
